version: "3"

services:
  linkin:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://linkin:linkin123@db:5432/linkin"
      HASHSALT: "1234" # random secret key
      NODE_ENV: "production"
    depends_on:
      - db
      - migrate

  migrate:
    build: .
    command: >
      sh -c "npm run prismamigrateprod
      && npm run seed"
    environment:
      DATABASE_URL: "postgres://linkin:linkin123@db:5432/linkin"
      HASHSALT: "123" # random secret key
      NODE_ENV: "production"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "linkin"
      POSTGRES_USER: "linkin"
      POSTGRES_PASSWORD: "linkin123"
    volumes:
      - linkin-data:/var/lib/postgresql/data
volumes:
  linkin-data:
